name: Checagem Fib-Fact

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Rodar checagem
      run: python3 Fib-Fact-Test/check.py

